name: Test

on: [push]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Tree
      uses: actions/checkout@v2
    - name: Create Container 
      run: |
        # docker build -t megatest --file Dockerfile .
    - name: Run Experiment
      run: |
        # mkdir -p logs output
        # while read command; do
        #   echo "Running command: $command"
        #   echo "---------------------------------------------------------------"
        #   docker run --name megatest_container megatest $command
        #   docker logs megatest_container >> logs/log 2>&1
        #   docker rm megatest_container
        #   echo "---------------------------------------------------------------"
        #   echo -e "\n\n\n"
        # done <list.25
    - name: Analyze Results
      run: |
        # pip install tqdm
        # python sort_by_error.py
        # cat package_report.txt
        # for i in output/*; do
        #   echo $i
        #   python summarize_error.py $i | tee $i.summary
        # done
        # python summarize_all_errors.py
        # cat stats.csv
        pip install jinja2
        python3 process_log.py
        

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
