name: Test

on: [push]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Tree
      uses: actions/checkout@v2
    - name: Create Container 
      run: |
        docker build -t megatest --file Dockerfile .
    - name: Run Experiment
      run: |
        while read command; do
          echo "Running command: $command"
          echo "---------------------------------------------------------------"
          docker run megatest $command
          echo "---------------------------------------------------------------"
          echo -e "\n\n\n"
        done <list.25
